### ISSUE TITLE
NuGet client version '2.8.1' or above, but the current NuGet version is '2.7.40911.287'

### ISSUE THREAD

**Issue by anujc** [Azure-Samples/active-directory-dotnet-native-headless#1]
I got the error NuGet client version '2.8.1' or above, but the current NuGet version is '2.7.40911.287'
I upgraded Visual Studio 2013 to Visual Studio 2013 Update 2 and the error disappeared.

We should probably mention Visual Studio 2013 Update 2 as a pre-requisite instead of Visual Studio 2013

**Comment by jmprieur** [comment]
now updated with support of VS 2017
