### ISSUE TITLE
AcquireTokenAsync method not return Token for Microsoft Account

### ISSUE THREAD

**Issue by prashantYL** [Azure-Samples/active-directory-dotnet-native-headless#11]
I have tried to use Microsoft account(i.e. user of @hotmail.com, outlook.com, live.com) to get the token. But AcquireTokenAsync throws an exception with blank message in Inner exception. I am unable to find out reason.  This user I have added in my AAD and given permission to access the application added in AAD.

It works fine with Microsoft AAD user and user created in AAD.
Please let me know is there is any specific setting required for Microsoft account.

**Comment by prashantYL** [comment]
As per the information available in this post This sample is not work with Microsoft account. 
Is there any way to implement for Microsoft account.

**Comment by jmprieur** [comment]
Indeed, to authenticate users with Microsoft personal accounts (MSA), you would need to use the AAD V2 endpoint, and MSAL.NET which does not yet support username/password and windows integrated authentication, but this is on the backlog.
