### ISSUE TITLE
AdalServiceException: accessing_ws_metadata_exchange_failed

### ISSUE THREAD

**Issue by ApiO** [Azure-Samples/active-directory-dotnet-native-headless#13]
Hi,

On the client project, when I try to get a token via :
`authContext.AcquireTokenAsync(SRV_RESX_ID, CLIENT_ID, uc).Result`

I get the following exception:

> `Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: accessing_ws_metadata_exchange_failed: Accessing WS metadata exchange failed ---> System.Net.Http.HttpRequestException:  Response status code does not indicate success: 406 (NotAcceptable)

For information I have follow all the steps and double check all the setup.
I use VS 2015 and ADAL 3+ (3.13.9).

Regards

**Comment by JLarue** [comment]
I am getting the same thing... here is the Fiddler capture...

GET https://login.microsoftonline.com/common/UserRealm/jakebenibble@gmail.com?api-version=1.0 HTTP/1.1
Accept: application/json
x-client-SKU: PCL.Desktop
x-client-Ver: 3.9.0.0
x-client-CPU: x64
x-client-OS: Microsoft Windows NT 6.2.9200.0
x-ms-PKeyAuth: 1.0
client-request-id: 073391c4-4cf6-466f-87f0-bebfb3595e59
return-client-request-id: true
Host: login.microsoftonline.com
Connection: Keep-Alive

RESPONSE 
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: application/json; charset=utf-8
Server: Microsoft-IIS/8.5
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Content-Disposition: inline; filename=userrealm.json
client-request-id: 073391c4-4cf6-466f-87f0-bebfb3596f59
x-ms-request-id: 10452322-aa50-46d1-a626-7b33a9c22900
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
Set-Cookie: esctx=AQABAAAAAABnfiG-mA6NTae7CdWW7QfdmpVRIQemR7Y5gpC8SvfgjAuO-uO4MgtO4gsyFz7vZJhhNLdMxJMB350xyFQYYysSfg7IpxbqEtHawpfpTJEaqyQ90nI0LwGRlKOe-g3bjj4dLtCIkOS97PO108MC9wN6beMPkTmbda-ZRMBJEA1PqN2ZxUyIYA9ukHtSvpO7NnMgAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly
Set-Cookie: x-ms-gateway-slice=007; path=/; secure; HttpOnly
Set-Cookie: stsservicecookie=ests; path=/; secure; HttpOnly
X-Powered-By: ASP.NET
Date: Tue, 27 Jun 2017 08:04:46 GMT
Content-Length: 363

{"ver":"1.0","account_type":"Federated","domain_name":"live.com","federation_protocol":"WSTrust","federation_metadata_url":"https://nexus.passport.com/FederationMetadata/2007-06/FederationMetadata.xml","federation_active_auth_url":"https://login.live.com/rst2.srf","cloud_instance_name":"microsoftonline.com","cloud_audience_urn":"urn:federation:MicrosoftOnline"}

**The Error occurs on the following request ...** 
GET https://nexus.passport.com/FederationMetadata/2007-06/FederationMetadata.xml HTTP/1.1
Accept: application/json
client-request-id: 073391c4-4cf6-466f-87f0-bebfb3595e59
return-client-request-id: true
Host: nexus.passport.com

RESPONSE is as follows

HTTP/1.1 406 Not Acceptable
Server: Microsoft-IIS/8.5
PPServer: PPV: 30 H: BL2IDSPRTS1C003 V: 0
Access-Control-Allow-Origin: *
Date: Tue, 27 Jun 2017 08:04:44 GMT
Connection: close
Content-Length: 0

So looks like a CORS related issue but am no expert so would appreciate some assistance.

**Comment by JLarue** [comment]
I further deployed just the code that is required to acquire a token into a ASP.Net Web API and deployed into Azure as a test... I purposefully am returning the exception so you can see ... passing in the username and password via the API call. 

https://pwtest20170627044331.azurewebsites.net/api/values/login/johnmkears@gmail.com/Passw0rd

**Comment by JLarue** [comment]
I just realized why that request is failing … it may not be a CORS issue after all but rather the client request has the response required to accept application/json… When I view the request in the browser it is returning as application/xml.   

This is the request that is failing …

https://nexus.passport.com/FederationMetadata/2007-06/FederationMetadata.xml

note that it returns XML and not JSON... Is there a reason for that?  Is there a way to change this to accept xml?

**Comment by jmprieur** [comment]
Are you using ADFS? is the server configured to provide SAML 2.0 tokens?

**Comment by 425BigData** [comment]
@jmprieur I'm getting this same error.  Newb to Azure and AD.    I need to configure AD to SAML 2.0 tokens?

**Comment by jmprieur** [comment]
cc: @brentschmaltz @henrik-me who will know better than I do.

**Comment by henrik-me** [comment]
This seems to be a B2C scenario given the link provided. This will not work with ADAL but only with MSAL (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/). Also at this point in time ADAL only supports federation with ADFS (if that is how you are connecting the identity system with the resources you are protecting). It will help a lot if you can describe the scenario in more detail.
