### ISSUE TITLE
Will this sample and pattern work with On Prem ADFS on 2016?

### ISSUE THREAD

**Issue by redshiftz** [Azure-Samples/active-directory-dotnet-native-headless#19]
Will this sample and pattern work with On Prem ADFS on 2016? I've been trying for days and getting "MSIS9602: The received 'resource' parameter is invalid. The authorization server can not find a registered resource with the specified identifier."

Thank you.

**Comment by kalyankrishna1** [comment]
did you follow any specific guidance. I'd recommend https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/enabling-oauth-confidential-clients-with-ad-fs.

**Comment by jmprieur** [comment]
@redshiftz : can you please tell us more about your resource (called Web API). did you register your application with https://portal.azure.com ? (is it a V1 resource)?

**Comment by Technicali** [comment]
The sample _should_ work. I have a .NET 4.7.1 console app inspired by the sample.
Can you describe how you configured your application group?
The error message to me indicates that the resource in your authorisation request is not the same as the identifier of your web api.

**Comment by jmprieur** [comment]
Closing this issue as we think it's a configuration issue (confirmed by Technicalli who has it working)
