### ISSUE TITLE
Error while running sample

### ISSUE THREAD

**Issue by sergsalo** [Azure-Samples/active-directory-dotnet-native-headless#2]
Hi, 
I made no changes to the sample. Only followed the instructions on how to run the sample. I receive next error:
"Message: AADSTS90014: The request body must contain the following parameter: 'client_secret or client_assertion'."
Inner Exception: The remote server returned an error: (400) Bad Request.

**Comment by Andreiaotto** [comment]
Hi vibronet, I am having the same error, but I configured as a native application, exactly how it is in the instruction. Any thing else it could be?
