### ISSUE TITLE
Readme needs a tweak

### ISSUE THREAD

**Issue by 425BigData** [Azure-Samples/active-directory-dotnet-native-headless#20]
Step 7 in Register the client app (TodoListClient-Headless)  can be removed.   With the Native app type there appears to be no App ID URI in the properties panel.    I think the URI is correctly updated in Step 3.

**Comment by jmprieur** [comment]
Thanks @425BigData. 
Indeed, the property appears when opening the blade, but it's now made invisible (because not needed). I've removed this step.
