### ISSUE TITLE
Inner Exception : accessing_ws_metadata_exchange_failed: Accessing WS metadata exchange failed

### ISSUE THREAD

**Issue by 425BigData** [Azure-Samples/active-directory-dotnet-native-headless#21]
I'm using the standard Azure AD service that came with my Office 365 subscription.    No AAD or code changes other then what the Readme.md called out.

**Comment by kellyelton** [comment]
Same problem

**Comment by jmprieur** [comment]
can you please share more about your ADFS ? you must be in an enterprise, which has an on-premise Active directory? which version? is it possible to share the exception ?

**Comment by kellyelton** [comment]
Azure Active directory. It's a 406 error Accessing WS metadata exchange.

**Comment by jmprieur** [comment]
you must be on a corporate network? (have an email address with a domain)? and your on-premise Active directory is federated with Azure Active directory. that's the topology and versions we'd need to understand.

**Comment by kellyelton** [comment]
I only have Azure Active Directory

**Comment by FcrNah** [comment]
Same issue.
I don't use any an premises ADs... Just active directory created with developer subscription.

**Comment by FcrNah** [comment]
It seems like plain login-pass method is disabled by Azure... Not sure here, please point to MS docs if you know.

In order to run this client you should replace following call in `Program.cs` (in two places):
> result = authContext.AcquireTokenAsync(todoListResourceId, clientId, uc).Result;

with
> var replyUrl = "https://pavelskletnojsideaportriga.onmicrosoft.com/TodoListClient-Headless";
> result = authContext.AcquireTokenAsync(todoListResourceId, clientId, new Uri(replyUrl), new PlatformParameters(0)).Result;

**Comment by jmprieur** [comment]
Thanks for the explanation, @FcrNah 
I understand what happened. you started from a sample which is for [Windows Integrated Authentication](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-Integrated-authentication-on-Windows-(Kerberos)) that is for domain joint machines, whereas you really wanted to do an interactive flow](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-interactively---Public-client-application-flows) with Azure AD.
you should look at the following sample: [active-directory-dotnet-native-desktop](https://github.com/Azure-Samples/active-directory-dotnet-native-desktop)
BTW it's WPF, but you don't really need a dialog. the following code also works:



```CSharp
// STS
string cloud = "https://login.microsoftonline.com";
string tenant = "pavelskletnojsideaportriga.onmicrosoft.com";
string authority = $"{cloud}/{tenantI}";

// Application
string clientId = "<your client id>";
Uri redirectUri = new Uri("https://pavelskletnojsideaportriga.onmicrosoft.com/TodoListClient-Headless");

// Application ID of the Resource (could also be the Resource URI)
string resource = "https://localhost:44321";

AuthenticationContext ac = new AuthenticationContext(authority);
AuthenticationResult result=null;
try
{
 result = await ac.AcquireTokenSilentAsync(resource, clientId);
}
catch (AdalException adalException)
{
 if (adalException.ErrorCode == AdalError.FailedToAcquireTokenSilently
     || adalException.ErrorCode == AdalError.InteractionRequired)
  {
   result = await ac.AcquireTokenAsync(resource, clientId, redirectUri,
                                       new PlatformParameters(PromptBehavior.Auto));
  }
}

proposing to close this issue. Feel free to reopen if this does not answer your question

**Comment by FcrNah** [comment]
@jmprieur, thanks for your response.
But it doesn't really resolves the issue.
I've dropped my comment as a workaround to make client app working. The sample as-is still throws exception from issue title...
