### ISSUE TITLE
UserCredential with ADFS error: AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'. 

### ISSUE THREAD

**Issue by mjendza** [Azure-Samples/active-directory-dotnet-native-headless#22]
Hi, 

I'm runing this sample with AFDS flow - When I'm trying to get the token - I'm getting an error:
`
Inner Exception : AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'.
Trace ID: 90ed39ca-2403-4efe-be94-6e237a060c00
Correlation ID: 94c8938b-5bf1-4103-8900-e0df04937f01
Timestamp: 2018-05-17 09:06:30Z`

Can I use the  UserCredential flow to AcquireToken when I have ADFS Flow ?

**Comment by jmprieur** [comment]
Yes, you should
are you sure you have registered your application as a public client application (See https://github.com/Azure-Samples/active-directory-dotnet-native-headless#register-the-client-app-todolistclient-headless, the *application type* needs to be **Native**)

**Comment by jmprieur** [comment]
Closing as there was no answer.
