### ISSUE TITLE
UserPasswordCredential is not supported in .NET Core

### ISSUE THREAD

**Issue by yanxiaodi** [Azure-Samples/active-directory-dotnet-native-headless#25]
I am trying to implement a backend API to call the Graph Intune APIs to configure the devices. According to the documentation of the Graph Intune API, it only allows the delegated permissions that means I cannot use the application permissions and I can only get the OAuth 2.0 token without user interactions to be on behalf of an admin user:

https://developer.microsoft.com/en-us/graph/docs/concepts/permissions_reference

https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/intune_deviceconfig_windows10customconfiguration_create

So I need to hard-code the admin username and the password in my project. I checked this repository but the UserPasswordCredential is not supported in .NET Core. I have searched a lot of documents and it makes me confused. If this kind of credential is not the recommended way, how to mock a user in the backend APIs? If it is impossible, why do Graph Intune APIs only accept delegated permissions? It is a deadlock. Any ideas? Thanks.

**Comment by jmprieur** [comment]
Hello @yanxiaodi 
did you consider using the on behalf of flow in the backend? 
See https://aka.ms/adal-net-on-behalf-of

**Comment by yanxiaodi** [comment]
@jmprieur  Thanks for your reply.
