### ISSUE TITLE
 unknown_user_type: Unknown User Type

### ISSUE THREAD

**Issue by LearnToCodeKM** [Azure-Samples/active-directory-dotnet-native-headless#26]
I am trying do the non-interactive login against **Azure AD B2C**, but I am getting error
unknown_user_type : Unknown User Type

**Comment by kalyankrishna1** [comment]
Hi, please provide more details. Is this a B2C tenant. What exactly is the code that is breaking?

**Comment by TiagoBrenck** [comment]
Closing because we are archiving this sample.
Please refer to these ones instead:

- https://github.com/Azure-Samples/active-directory-dotnet-iwa-v2 for integrated windows authentication
- https://github.com/azure-samples/active-directory-dotnetcore-console-up-v2 for username/password
