### ISSUE TITLE
Startup.Auth.cs is required for token to be acquired using username and password? [question]

### ISSUE THREAD

**Issue by AhambaliJ** [Azure-Samples/active-directory-dotnet-native-headless#27]
I have a question regarding startup.auth.cs. Is this code required by the service for this type of token acquiring to work.

I have a console app that successfully acquire token interactively but when I tried using username and password. It gave me an error of accessing_ws_metadata_exchange_failed.

Thank you.

**Comment by jmprieur** [comment]
@AhambaliJ 
which is your configuration? what authority do you use in the Client ? are you on a corporate environment?

Can you please provide repro steps and also more information about the errror? is it an exception? 
if this is an Adal exception, you might want to [enable logging](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Logging-in-ADAL.Net)?

**Comment by AhambaliJ** [comment]
Hi @jmprieur,

Thank you for the reply.

I'm not quite sure which configuration do you mean, so I'll just shoot a few and let me know if I got it right or wrong.

My WebAPI config is the default config when you create one in Visual Studio 2017. I have not meddle with the config at all hence the question.
The WebAPI application service config on Azure is default, published using the Visual Studio with express config Active Directory Authentication.
The WebAPI AAD application config is as when it is created automatically by Azure.

My Native AAD application config is default except for permission. I've added a delegated permission to allow access to my WebAPI with Requires Admin : No.

Authority on client is on Global Admin, as I'm the only one user.
I'm on my own private environment, so I'm not in a corporate environment.

My repro steps would be as follow:

1. Create a WebAPI with a custom endpoint to return a number.
2. Deploy and publish WebAPI on Azure.
3. Create console application and access the unsecured endpoint (success)
4. Turn on WebAPI App Service Authentication, configure Azure Active Directory Authentication Provider using express setup (I believe an Azure Active Directory application is created automatically for WebAPI at this point).
5. Create new application as Native Application on Azure Active Directory.
6. Add required permission, select the WebAPI  and add Delegated Permission.
7. Try to authenticate interactively with PromptBehaviour.Always and access endpoint securedly (success)
8. Try to authenticate using Device Code Flow and access enpoint securedly (success).
9. Try to authenticate silently using username/password and access endpoint ( failed at authentication)

I'm not sure whether it is an ADAL exception, the console application caught AdalServiceException : Response status code does not indicate success : 406 (NotAcceptable).

Exception occured at 6 different location: 
- Microsoft.Identity.Core.WsTrust.WsTrustWebRequestManaget.<GetMexDocumentAsync>d__3.MoveNext()
- Microsoft.Identity.Core.WsTrust.CommonNonInteractiveHandler.<PerformWsTrustMexExchangeAsync>d__7.MoveNext()
- Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenUsernamePasswordHandler.<PreTokenRequestAsync>d__5.MoveNext()
- Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__53.MoveNext()
- Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__40.MoveNext()
- Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContextIntegratedAuthExtensions.<AcquireTokenAsync>d__0.MoveNext()
- ConsoleApp1.Program.<CallWebApiProtectedAsync>d__2.MoveNext() in my console application.

**Comment by kalyankrishna1** [comment]
@AhambaliJ , App Service Authentication uses a wrapper over authentication called [EasyAuth](https://docs.microsoft.com/en-us/azure/app-service/app-service-authentication-overview). It has slightly different semantics and I'd suggest you get yourself familiar with that before trying the code in this sample

**Comment by AhambaliJ** [comment]
Hi @kalyankrishna1. Thank you for the reply. I have gone through the app service authentication overview that you have linked. 

I still have no clue on how to proceed.

My next question would be this. Do I miss a step somewhere? Do I need a custom configuration on my WebAPI app. 

I have tried using MSAL. The result is identical. Still get status code 406 and accessing_ws_metadata_exchange_failed.

I have made change to my WebAPI manifest and allow for public application by setting true to allowPublicClient.

Would be great if you can redirect me the next steps.

Thank you again @kalyankrishna1

**Comment by TiagoBrenck** [comment]
Closing because we are archiving this sample.
Please refer to these ones instead:

- https://github.com/Azure-Samples/active-directory-dotnet-iwa-v2 for integrated windows authentication
- https://github.com/azure-samples/active-directory-dotnetcore-console-up-v2 for username/password
