### ISSUE TITLE
Able to login with incorrect password on second attempt 

### ISSUE THREAD

**Issue by LearnToCodeKM** [Azure-Samples/active-directory-dotnet-native-headless#28]
I am trying achieve headless using web API, I created a API which take username and password, it does not have the Authorize filter. I am able to get a valid access token, but I am able to authenticate user using invalid password from the second attempt. Below is my sample code 

    public class LoginController : ApiController
    {
        private static string aadInstance = System.Configuration.ConfigurationManager.AppSettings["ida:AADInstance"];
        private static string tenant = ConfigurationManager.AppSettings["ida:Tenant"];
        private static string clientId = ConfigurationManager.AppSettings["ida:ClientId"];
        private static string authority = String.Format(CultureInfo.InvariantCulture, aadInstance, tenant);
       
        private static string todoListResourceId = ConfigurationManager.AppSettings["todo:TodoListResourceId"];
        private static string todoListBaseAddress = ConfigurationManager.AppSettings["todo:TodoListBaseAddress"];
        // GET api/todolist
        [HttpGet]
        [Route("api/Todo/Login/{password}")]
        public async System.Threading.Tasks.Task<string> LoginAsync(string password)
        {
             var authContext = new AuthenticationContext(authority);
            UserCredential uc = new UserPasswordCredential("<upn>", password);
            AuthenticationResult result = authContext.AcquireTokenAsync(todoListResourceId, clientId, uc).Result;
            

            return result.AccessToken;
        }
    }

**Comment by jmprieur** [comment]
@LearnToCodeKM 
Username password is a public client application flow (for desktop / mobile applications). you should not use it in Web APIs (which are confidential client applications).  Did you consider other approaches like what is described in: https://github.com/azure-samples/active-directory-dotnet-native-aspnetcore-v2 ?

**Comment by LearnToCodeKM** [comment]
> @LearnToCodeKM
> Username password is a public client application flow (for desktop / mobile applications). you should not use it in Web APIs (which are confidential client applications). Did you consider other approaches like what is described in: https://github.com/azure-samples/active-directory-dotnet-native-aspnetcore-v2 ?

**Comment by jmprieur** [comment]
?

**Comment by LearnToCodeKM** [comment]
I am sorry for confusion, i clicked on 'Close and comment' instead of 'Comment'.

I did take a look at the approach mentioned in : https://github.com/azure-samples/active-directory-dotnet-native-aspnetcore-v2  but it was not fruitful. 

Here is my scenario:
I am trying to create a API which can get access token for the  given user name and password and this web API is accessed by multiple applications. I building this API against Azure AD B2C. 
I not able to find any solution to achieve this. Any help in this regard is very much helpful.

**Comment by jmprieur** [comment]
@LearnToCodeKM 
The headless sample features several flows (U/P, but also integrated windows authentication).

 I recommend you move to MSAL.NET and use the following sample: https://github.com/Azure-Samples/active-directory-dotnetcore-console-up-v2 . It's simpler, and MSAL.NET is the new generation of libraries

Conceptual doc for the flow you want to use: https://aka.ms/msal-net-up

**Comment by LearnToCodeKM** [comment]
The App Registration(preview)  is not available in Azure AD B2C. I cannot use MSAL.Net .

**Comment by jmprieur** [comment]
You should be able to use MSAL.NET, but by registering your app in B2C. Adding @valnav for guidance.

**Comment by LearnToCodeKM** [comment]
@valnav can you guide me on how to use MSAL.NET with Azure B2C?. Any references will help me. Thank you.

**Comment by jmprieur** [comment]
@LearnToCodeKM : did you read https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specificities ?

**Comment by LearnToCodeKM** [comment]
> @LearnToCodeKM : did you read https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specificities ?

The above link is using B2C policies which is not a headless authentication.

**Comment by LearnToCodeKM** [comment]
I did find this https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Username-Password-Authentication , but i just wanted to know what should be the client id and the process to register the app.

**Comment by LearnToCodeKM** [comment]
I was able to authenticate the user using MSAL.net with Azure B2C, but I am not able to secure my API using that token. Is there any way to do it?
Is it possible to tweak this solution to meet the token received from MSAL 
https://jonhilton.net/security/apis/secure-your-asp.net-core-2.0-api-part-2---jwt-bearer-authentication/

**Comment by jmprieur** [comment]
@LearnToCodeKM : you might want to have a look at this sample: https://github.com/azure-samples/active-directory-dotnet-native-aspnetcore-v2
Again it's not for B2C, but this should also work for B2C.

**Comment by TiagoBrenck** [comment]
Closing because we are archiving this sample.
Please refer to these ones instead:

- https://github.com/Azure-Samples/active-directory-dotnet-iwa-v2 for integrated windows authentication
- https://github.com/azure-samples/active-directory-dotnetcore-console-up-v2 for username/password
