### ISSUE TITLE
I keep getting the "No permission to access user information..." error

### ISSUE THREAD

**Issue by jan-tamas** [Azure-Samples/active-directory-dotnet-native-headless#3]
Hi, I followed the tutorial, but when I run "add" in the client, I enter the username and password and then get an error with the message: AADSTS65001: No permission to access user information is configured for '<client GUID here>' application, or it is expired or revoked.
Can you help me resolve this issue? It appears both with the service running locally as well as with the service running in Azure website.
Thanks.
Jan

**Comment by qjuanp** [comment]
@jan-tamas check this issue, https://github.com/Vtek/PowerBI.Api.Client/issues/1 I think it shuld be helpfull

**Comment by jan-tamas** [comment]
I don't see how this relates to the bug/issue in the tutorial. Can you be more specific?

**Comment by dstrockis** [comment]
Hey @jan-tamas, sorry for the delay in response here.  This usually has to do with your client app not having the correct permissions to access the API.  Can you confirm that you have set up the right permissions in the "Permissions to other Applications" section in the portal?

You should also consider the "Constraints & Limitations" section in this blog post: http://www.cloudidentity.com/blog/2014/07/08/using-adal-net-to-authenticate-users-via-usernamepassword/

**Comment by mandarsudame** [comment]
I am also getting the same issue : No permission to access user information is configured for '<ClientId removed>' application, or it is expired or revoked. 

Interesting thing is if I use Windows integrated auth and pass in the default ctor UserCredential(), token acquisition works. This tells me that my configuration is correct.
But when I use UserCredential(username, password) I get the above exception.

**Comment by cicorias** [comment]
I get the same error here.  Followed the readme and error message: 

An unexpected error occurred.
Message: AADSTS65001: No permission to access user information is configured for '699ab084-9745-423c-9695-97b4d2156dc7' application,
 or it is expired or revoked.
Trace ID: 0d23bfc5-959f-4ed4-be93-3bf39b6e7914
Correlation ID: 98d07d32-d7cd-4106-9b82-37c78e687915
Timestamp: 2015-06-05 19:03:28Z
Inner Exception : The remote server returned an error: (400) Bad Request.

**Comment by jan-tamas** [comment]
@dstrockis I believe I have all the permissions set up correctly. As @cicorias has the same error, the problem probably isn't on my side...

**Comment by nimatra** [comment]
Could anyone solve this issue?

**Comment by g-amador** [comment]
I had this problem because in the app.config I put the wrong ClientId. The correct one is the ClientID **not** the ToDoListService ClientId (AppId). Working for me now.
