### ISSUE TITLE
Acquire JWT Token Silently

### ISSUE THREAD

**Issue by milanid** [Azure-Samples/active-directory-dotnet-native-headless#30]
My aim is to acquire silently an Azure AD token from a Domain joined workstation whose domain is connected to Azure AD through Azure AD Connect.
In order to do that I've built the following scenario:
- I configured a Windows Server and an Active Domain on it
- I connected the Active Domain to Azure AD using Azure AD Connect
- I configured the Seamless Sign-On: in fact, if I use a web-browser from a domain joined machine to navigate to the url https://myapps.microsoft.com/my_azure_domain.onmicrosoft.com I'm logged in correctly without user interaction
- If I use this project in order to obtain an Azure AD JWT Token interactively from a domain joined workstation (using the Textual Prompt) everything works fine
- If I use this project in order to obtain an Azure AD JWT Token silently from a domain joined workstation (using the Windows-integrated security - UserCredential) I obtain the following error:
Inner Exception : password_required_for_managed_user: Password is required for managed user

What am I missing?
Thanks,
Daniele

**Comment by kalyankrishna1** [comment]
The answer has been provided [here on SO](https://stackoverflow.com/questions/50919092/get-error-password-is-required-for-managed-user-when-authenticating-user-with). If the answer does not apply to you, please expand the question with the following details
1. The code that has been written for the last two steps
2. Is the user account being used the same one for both the cases. And the user exists in both on-prem AD and Azure AD.

**Comment by milanid** [comment]
Hi,
thanks for your answer: I cloned this github project and I run it, so I used the code provided here (https://github.com/Azure-Samples/active-directory-dotnet-native-headless/blob/master/TodoListClient/Program.cs#L205).
For what concerns the account, I confirm that is the same for both cases, and exists both on-prem AD and on Azure AD.

Thanks,
Daniele

**Comment by milanid** [comment]
P.S.: If I use this MSAL example (https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-desktop-msgraph-v2/) everything works.

**Comment by jmprieur** [comment]
@milanid what about this one: https://github.com/azure-samples/active-directory-dotnet-iwa-v2 ?

**Comment by milanid** [comment]
My aim was to use ADAL instead of MSAL: in fact, from my undestanding the development of the MSAL library is still ongoing and right now it is not suitable to use it in a production environment. Am I right?

**Comment by milanid** [comment]
@jmprieur I tried the example you suggested, and I obtained the following output
_Integrated Windows Auth is not supported for managed users. See https://aka.ms/msal-net-iwa for details._
I think that my federated users are recognized as managed.

**Comment by jmprieur** [comment]
MSAL is production supported (many customers use it). But we don't guaranty that there won't be breaking change before we GA (there will actually be a few in the 2 coming weeks when we release MSAL.NET 3.0)

yes, I think that your users are not recognized as federated. would that be a configuration thing?

**Comment by milanid** [comment]
Yes, I was thinking about a configuration thing too, how can I check if everything is configured correctly?

**Comment by milanid** [comment]
Solved by replacing this code (file TodoListClient/Program.cs)

    authContext.AcquireTokenAsync(todoListResourceId, clientId, uc)

with this one

    `authContext.AcquireTokenAsync(todoListResourceId, clientId, new Uri("http://TodoListClient-Headless"), new PlatformParameters(PromptBehavior.Auto)).Result`

I think it could be a good idea to update the readme and to add two commented lines in the Program.cs file...

**Comment by jmprieur** [comment]
@milanid : I'm glad this solves your issue
However, your code does not use Integrated windows authentication in that case. That's an interactive authentication where you happened to have authenticated already, and therefore this works (probably not the first time).

Proposing to close this issue as you have it working?

**Comment by milanid** [comment]
In my scenario is not interactive (the Seamless SSOis configured, and the user doesn't have to perform the login manually).
Actually I don't think that it is possible to use IWA in my scenario (AD synchronized with Azure AD through Azure AD Connect & Seamless SSO).
Anyway, for me it's okay to close the issue.

**Comment by jmprieur** [comment]
Thanks for sharing your scenario. we'll add something in the conceptual documentation
cc: @bgavrilMS

**Comment by milanid** [comment]
Thanks!

**Comment by milanid** [comment]
One last thing: if my understanding is right (IWA non working with Seamless SSO), I think you have to change this page https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/adal-and-seamless-sso#which-versions-of-adal-work-with-azure-add-seamless-sso.
