### ISSUE TITLE
Response status code does not indicate success: 406

### ISSUE THREAD

**Issue by stephenweinrich** [Azure-Samples/active-directory-dotnet-native-headless#31]
Following the instructions in the repo and setting up the application on my AAD I get this following error:

AdalServiceException: Response status code does not indicate success: 406 (NotAcceptable).

Is this method of authentication using UserPasswordCredential even still supported by AAD? DotNetCore are no longer supporting this method.

Will it work on ADFS?

**Comment by TiagoBrenck** [comment]
Closing because we are archiving this sample.
Please refer to these ones instead:

- https://github.com/Azure-Samples/active-directory-dotnet-iwa-v2 for integrated windows authentication
- https://github.com/azure-samples/active-directory-dotnetcore-console-up-v2 for username/password
