### ISSUE TITLE
Can't run the scripts, 

### ISSUE THREAD

**Issue by jamacia** [Azure-Samples/active-directory-dotnet-native-headless#33]
When I try to run the scripts it says they are not  signed digitally and can not be run
Can you help me ?

**Comment by jmprieur** [comment]
@jamacia 
did you read https://github.com/Azure-Samples/active-directory-dotnet-native-headless/blob/master/AppCreationScripts/AppCreationScripts.md ?

you need to run `Set-ExecutionPolicy -Scope Process -ExecutionPolicy Unrestricted` first.

**Comment by jmprieur** [comment]
Closing this issue as it was answered (a long time ago)
