### ISSUE TITLE
client_secret error when running TodoListClient

### ISSUE THREAD

**Issue by scilligence** [Azure-Samples/active-directory-dotnet-native-headless#34]
Can anyone help on this error when running TodoListClient?
------------------------
Enter command (list | add | clear | exit | help) >
list
No token in the cache
There is no token in the cache or you are not connected to your domain.
Please enter username and password to sign in.
User>
XXXXX@XXXXX.onmicrosoft.com
Password>
xxxxxxxxxxxxx
An unexpected error occurred.
Message: One or more errors occurred.
**Inner Exception : AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.**
Trace ID: e5fe8c16-5410-4ea2-8636-27394e6d6100
Correlation ID: 4aaeb83e-d592-43c9-8142-3bbd3d96e8af
Timestamp: 2019-05-06 18:25:34Z
Enter command (list | add | clear | exit | help) >

**Comment by kalyankrishna1** [comment]
This is an older sample and might be archived soon. Please try the new sample [here](https://github.com/Azure-Samples/active-directory-dotnet-iwa-v2)

**Comment by jiria** [comment]
Hello Kalyan, the new sample you are pointing to is not a direct replacement for this sample. Do you have something more similar?

**Comment by TiagoBrenck** [comment]
Closing because we are archiving this sample.
Please refer to these ones instead:

- https://github.com/Azure-Samples/active-directory-dotnet-iwa-v2 for integrated windows authentication
- https://github.com/azure-samples/active-directory-dotnetcore-console-up-v2 for username/password
