### ISSUE TITLE
always getting : missing federation metadata url

### ISSUE THREAD

**Issue by WahidBitar** [Azure-Samples/active-directory-dotnet-native-headless#5]
I added my APP ID as resource Id but still always get this error:

missing_federation_metadata_url:  Federation Metadata Url is missing for federated user. This user type is unsupported.

**Comment by bengaspar** [comment]
Same here, any updates on this?

**Comment by vijayaramb** [comment]
i am also getting this issue. I am trying in web api service. This works in console application

**Comment by arvis811** [comment]
I get "missing_federation_metadata_url: Federation Metadata Url is missing for federated user. This user type is unsupported." error too. 

Any one could help with this, please?

**Comment by jmprieur** [comment]
you are probably using ADFS, and your server is not configured to provide SAML 2.0 tokens?
