### ISSUE TITLE
UserCredential in UWP

### ISSUE THREAD

**Issue by aline-almeida** [Azure-Samples/active-directory-dotnet-native-headless#7]
Hi!
I've tried to use this in a UWP app, but the constructor of UserCredential doesn't accept a password...

How can I overcome this?

Thanks
Aline

**Comment by aline-almeida** [comment]
Any info on this ?
I need to release may app ASAP...
Thanks
Aline

**Comment by jmprieur** [comment]
In UWP you would probably want to use the Windows Integrated Authentication. Please see https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-Integrated-authentication-on-Windows-(Kerberos)

See also https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-a-token-return-AuthenticationResult-and-possibly-UserInfo#summary-for-public-client-applications for the list of supported grants for public client applications.
